### ISSUE TITLE
Error when building UTP theories

### ISSUE THREAD

**Issue by CThuleHansen** [isabelle-utp/utp-main#3]
When building the UTP theories with ```isabelle jedit -d path/utp-main/ -l UTP``` 
I get the following error: 

UTP FAILED
(see also C:\Users\ctha\.isabelle\Isabelle2016\heaps\polyml-5.6_x86-windows\log\UTP)

```

***                                                   

*** l.1 \BOOKMARK [1][-]{section.1}{UTP variables}{}

***                                                 % 1

*** !  ==> Fatal error occurred, no output PDF file produced!

*** Transcript written on root.log.

*** Document preparation failure in directory 'output/document'
*** 
*** Failed to build document "/cygdrive/c/source/isabelle/utp-main/utp/output/document.pdf"
*** Undefined fact: "list_minus_anhil" (line 349 of "/cygdrive/c/source/isabelle/utp-main/utp/utp_csp.thy")
*** At command "using" (line 349 of "/cygdrive/c/source/isabelle/utp-main/utp/utp_csp.thy")
*** Undefined fact: "list_minus_anhil" (line 367 of "/cygdrive/c/source/isabelle/utp-main/utp/utp_csp.thy")
*** At command "apply" (line 367 of "/cygdrive/c/source/isabelle/utp-main/utp/utp_csp.thy")
*** Undefined fact: "list_minus_anhil" (line 301 of "/cygdrive/c/source/isabelle/utp-main/utp/utp_csp.thy")
*** At command "using" (line 301 of "/cygdrive/c/source/isabelle/utp-main/utp/utp_csp.thy")
Unfinished session(s): UTP
Return code: 2

Session build failed -- prover process remains inactive!
```

It seems to be related to this commit: https://github.com/isabelle-utp/utp-main/commit/fdf555ef3b8c01828d558f460c9e608c410783c1

**Comment by ldcouto** [comment]
I get this same error. We suspect this could be related to some commented stuff in  line 135 in list_extra.thy

@simondfoster , it would be nice if there was a version of the theories that always builds. Maybe you could just cut a releases with tags? This way, we know what to checkout and build.

**Comment by CThuleHansen** [comment]
Currently attempting this commit
https://github.com/isabelle-utp/utp-main/commit/3fef1987c6312601e2a910acc7aedf171e6abe94

**Comment by simondfoster** [comment]
Sorry about this. It should be fixed in the newest version. @ldcouto good idea - we can use the release branch and maybe make monthly releases.

**Comment by CThuleHansen** [comment]
Hi Simon, Thank you!

can you give us access to push to the repo or will you merge master to release branch?

**Comment by CThuleHansen** [comment]
@simondfoster I am still having some issues building the new stuff, but it is due to latexing. 
The location can be discovered if running pdflatex on root.tex.
It works fine in this commit: https://github.com/isabelle-utp/utp-main/commit/3fef1987c6312601e2a910acc7aedf171e6abe94

**Comment by ldcouto** [comment]
I have access to the repo. I can give it to you @CThuleHansen

**Comment by CThuleHansen** [comment]
Looks like Frank addressed it in https://github.com/isabelle-utp/utp-main/commit/a056928f68c50ea15cf639156de7f7270a0309a1|
Master now builds.
